# Generated by Django 4.2 on 2026-02-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='username',
            field=models.CharField(default='unknown_user', max_length=150),
        ),
    ]
